// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zivyygsojoehavbkodtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inppdnl5Z3Nvam9laGF2YmtvZHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMjk0MDUsImV4cCI6MjA1MjkwNTQwNX0.CKeJsphTOBZLVvmI45f1Ygfep1Je81bxIzWwpUVk3gM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);